import"./assets/modulepreload-polyfill-B5Qt9EMX.js";/* empty css                      */import{f as g,i}from"./assets/vendor-BbbuE1sJ.js";let n,l=null;const o=document.querySelector("[data-start]"),u=document.querySelector("#datetime-picker");o.disabled=!0;const p=document.querySelector("[data-days]"),h=document.querySelector("[data-hours]"),y=document.querySelector("[data-minutes]"),S=document.querySelector("[data-seconds]"),b={enableTime:!0,time_24hr:!0,defaultDate:new Date,minuteIncrement:1,onClose(e){const t=e[0];if(t<=new Date){o.disabled=!0,i.destroy(),i.show({id:null,class:"",title:"",titleColor:"black",titleSize:"",titleLineHeight:"",message:`
  <div style="display:flex;align-items:center;gap:8px">
    <svg width="40" height="40">
      <use href="../img/sprite.svg#icon-close"></use>
    </svg>
    <span>Please choose a date in the future</span>
  </div>
  `,messageColor:"black",messageSize:"",messageLineHeight:"",backgroundColor:"",theme:"dark",color:"red",icon:"",iconText:"",iconColor:"black",iconUrl:null,image:"",imageWidth:50,maxWidth:null,zindex:null,layout:1,balloon:!1,close:!1,closeOnEscape:!1,closeOnClick:!1,displayMode:0,position:"topRight",target:"",targetFirst:!0,timeout:0,rtl:!1,animateInside:!0,drag:!0,pauseOnHover:!0,resetOnHover:!1,progressBar:!1,progressBarColor:"",progressBarEasing:"linear",overlay:!1,overlayClose:!1,overlayColor:"rgba(0, 0, 0, 0.6)",transitionIn:"fadeInUp",transitionOut:"fadeOut",transitionInMobile:"fadeInUp",transitionOutMobile:"fadeOutDown",buttons:{},inputs:{},onOpening:function(){},onOpened:function(){},onClosing:function(){},onClosed:function(){}});return}else{i.destroy(),n=t,o.disabled=!1;return}}};g("#datetime-picker",b);function a(e){const d=Math.floor(e/864e5),c=Math.floor(e%864e5/36e5),f=Math.floor(e%864e5%36e5/6e4),m=Math.floor(e%864e5%36e5%6e4/1e3);return{days:d,hours:c,minutes:f,seconds:m}}o.addEventListener("click",()=>{o.disabled=!0,u.disabled=!0,l=setInterval(()=>{if(n-new Date<=0){clearInterval(l),u.disabled=!1;return}let e,t,s,r;e=a(n-new Date).days,t=a(n-new Date).hours,s=a(n-new Date).minutes,r=a(n-new Date).seconds,p.textContent=e.toString().padStart(2,"0"),h.textContent=t.toString().padStart(2,"0"),y.textContent=s.toString().padStart(2,"0"),S.textContent=r.toString().padStart(2,"0")},1e3)});
//# sourceMappingURL=1-timer.js.map
